USE TEMPDB;
INSERT INTO MSLEARN.PERSON_ADDRESS(PERSON_ID, ADDRESS_ID,ADDRESS_TYPE_CD) VALUES (16496,25580,'HA');
INSERT INTO MSLEARN.PERSON_ADDRESS(PERSON_ID, ADDRESS_ID,ADDRESS_TYPE_CD) VALUES (12506,21576,'HA');
INSERT INTO MSLEARN.PERSON_ADDRESS(PERSON_ID, ADDRESS_ID,ADDRESS_TYPE_CD) VALUES (11390,20457,'HA');