CREATE SCHEMA MSLEARN;
GO

CREATE TABLE MSLEARN.TEMP (
ID INT,
VAL VARCHAR(10)
);
DELETE FROM MSLEARN.TEMP;

BEGIN TRANSACTION
INSERT INTO MSLEARN.TEMP VALUES (1,'ABC'),(2,'DEF');
SELECT * FROM MSLEARN.TEMP;
PRINT 'BEFORE ROLLBACK @@TRANCOUNT = '+CAST( @@TRANCOUNT AS CHAR(4))+'  @@ROWCOUNT = '+CAST(@@ROWCOUNT AS CHAR(4));
ROLLBACK;
PRINT 'AFTER ROLLBACK @@TRANCOUNT = '+CAST( @@TRANCOUNT AS CHAR(4))+'  @@ROWCOUNT = '+CAST(@@ROWCOUNT AS CHAR(4));
SELECT * FROM MSLEARN.TEMP;

BEGIN TRANSACTION
INSERT INTO MSLEARN.TEMP VALUES (1,'ABC'),(2,'DEF');
SELECT * FROM MSLEARN.TEMP;
PRINT 'BEFORE COMMIT @@TRANCOUNT = '+CAST( @@TRANCOUNT AS CHAR(4))+'  @@ROWCOUNT = '+CAST(@@ROWCOUNT AS CHAR(4));
COMMIT;
PRINT 'AFTER COMMIT @@TRANCOUNT = '+CAST( @@TRANCOUNT AS CHAR(4))+'  @@ROWCOUNT = '+CAST(@@ROWCOUNT AS CHAR(4));
SELECT * FROM MSLEARN.TEMP;